version: '3'

services:
  web:
    container_name: unique-bundle-store
    image: unique-bundle-store:latest
    command: sh -c "rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    tty: true
    stdin_open: true
    depends_on:
      - mysql
      - redis
    restart: always
    networks:
      - network

  mysql:
    image: mysql:8.0
    container_name: unique-bundle-store-db
    environment:
      MYSQL_ROOT_PASSWORD: senha@123
      MYSQL_USER: admin
      MYSQL_PASSWORD: senha@123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    restart: always
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: unique-bundle-store-php-myadmin
    restart: always
    ports:
      - 3001:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - network

  redis:
    image: redis:6.2
    container_name: unique-bundle-store-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - network

networks:
  network:
